spring: 
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
   username: root
   password: 123456
 cloud:
  config:
   server:
    git:
     basedir: D:\Log